[displays.niri.desktop]
main = "Razer Taiwan Co. Ltd. RZ39-0276 2034V03502864"
side = "ASUSTek COMPUTER INC ASUS VG249 0x00016804"

[displays.hypr.desktop]
main = "Razer Taiwan Co. Ltd. RZ39-0276"
side = "ASUSTek COMPUTER INC ASUS VG249"
