# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#windowrule = nomaximizerequest, class:.* # You'll probably like this.
windowrule = float on,match:class ^(com\.github\.hluk\.copyq)$
#windowrule = stayfocused,class:^(com\.github\.hluk\.copyq)$
#windowrule = move onscreen cursor -50% -50%,class:^(com\.github\.hluk\.copyq)$
windowrule = float on,match:class ^(feh)$
windowrule = float on,match:class ^(swayimg)$
windowrule = float on,match:class ^(imv)$
windowrule = float on,match:class ^(Sxiv)$
windowrule = float on,match:class ^(Nsxiv)$
windowrule = float on,match:class ^(love)$
windowrule = float on,match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on,match:initial_class ^(?!org\.godotengine)(.),match:initial_title ^(Godot)$
windowrule = render_unfocused on,match:class ^(com.libretro.RetroArch)$

windowrule = workspace 4,match:class ^(firefox)$
windowrule = workspace 4,match:class ^(zen)$
windowrule = workspace 3,match:class ^(vesktop)$
windowrule = workspace 5,match:class ^(steam)$,match:title ^(?!notificationtoasts).

windowrule = pseudo on,match:initial_class kitty,match:workspace w[1],match:workspace name:special:term
windowrule = size 60% 70%,match:initial_class kitty,match:workspace w[1],match:workspace name:special:term

windowrule = render_unfocused on,match:class ^(pokeclicker-desktop)$
windowrule = animation popin, match:fullscreen 1
windowrule = float on,match:class zen,match:initial_title ^(Picture-in-Picture)$
windowrule = pin on,match:class zen,match:initial_title ^(Picture-in-Picture)$


workspace = 3,monitor:DP-2,name:chat

windowrule = border_size 0, match:tag noborder

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

