(deftheme Lunacy
  "Luna's Lunacy Theme")

(custom-theme-set-faces
 'Lunacy
 '(cursor ((t (:background "white smoke"))))
 '(fixed-pitch ((t (:family "Terminus"))))
 '(variable-pitch ((t (:weight normal :family "Cantarell"))))
 '(escape-glyph ((t (:foreground "orange" :weight extra-bold))))
 '(homoglyph ((t (:weight bold :foreground "#ddaa6f"))))
 '(minibuffer-prompt ((t (:foreground "green"))))
 '(highlight ((t (:underline t :foreground "yellow" :background "#000044"))))
 '(region ((t (:extend t :background "dark slate blue"))))
 '(shadow ((t (:background "black" :foreground "white"))))
 '(secondary-selection ((t (:extend t :foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "orange"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#80a0ff"))))
 '(font-lock-constant-face ((t (:foreground "orange"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "cyan"))))
 '(font-lock-keyword-face ((t (:foreground "white"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "green"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "yellow"))))
 '(font-lock-type-face ((t (:foreground "light green" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "cyan"))))
 '(font-lock-warning-face ((t (:background "dark goldenrod" :foreground "white"))))
 '(button ((t (:background "#000044" :foreground "white" :underline t))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#8ac6f2"))))
 '(link-visited ((t (:foreground "medium purple" :underline t))))
 '(fringe ((t (:background "#000044"))))
 '(header-line ((t (:foreground "violet" :underline t))))
 '(tooltip ((t (:foreground "white" :background "navy" :inherit variable-pitch))))
 '(mode-line ((t (:background "navy" :foreground "white"))))
 '(mode-line-buffer-id ((t (:background "#dd65dd"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:background "blue" :foreground "yellow"))))
 '(mode-line-inactive ((t (:background "slate gray" :foreground "white"))))
 '(isearch ((t (:background "medium blue" :foreground "white"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#a0a8b0" :background "#384048"))))
 '(match ((t (:background "medium blue"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(line-number ((t (:background "#000044" :foreground "#999999"))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "violet"))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground "#AA88FF"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#2288ff"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "cyan1"))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "green"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "yellow"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "gold"))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "orange"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground "dark orange"))))
 '(rainbow-delimiters-base-error-face ((t (:foreground "white" :background "dark red" :inherit rainbow-delimiters-base-face))))
 '(org-table ((t (:inherit (shadow fixed-pitch) :foreground "gold"))))
 '(org-default ((t (:inherit default :background "gray10"))))
 '(org-block-begin-line ((t (:inherit (fixed-pitch shadow) :extend t :foreground "dark slate blue" :weight bold))))
 '(org-block-end-line ((t (:inherit org-block-begin-line :extend t :foreground "dark slate blue"))))
 '(org-hide ((t (:foreground "Gray10"))))
 '(org-indent ((t (:inherit (org-hide)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "light gray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 162 :width normal :foundry "Xos4" :family "Terminus")))))

(provide-theme 'Lunacy)
